"""models de moto

Revision ID: 01061de02077
Revises: 7d350c8b2688
Create Date: 2025-11-28 18:46:58.102949

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01061de02077'
down_revision: Union[str, Sequence[str], None] = '7d350c8b2688'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('playing_with_neon')
    op.add_column('motos', sa.Column('ano', sa.Integer(), nullable=True))
    op.alter_column('motos', 'marca',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('motos', 'modelo',
               existing_type=sa.VARCHAR(),
               nullable=False)
    

    op.alter_column('motos', 'dono_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               server_default='1'
    )
    op.alter_column('motos','dono_id',server_default=None)
    

    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_unique_constraint(None, 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.alter_column('users', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('motos', 'dono_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('motos', 'modelo',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('motos', 'marca',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('motos', 'ano')
    op.create_table('playing_with_neon',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('value', sa.REAL(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('playing_with_neon_pkey'))
    )
    # ### end Alembic commands ###
