"""projeto com jwt

Revision ID: 0f7fc20fc217
Revises: 
Create Date: 2025-09-05 15:18:32.227464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7fc20fc217'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usuarios2_id'), table_name='usuarios2')
    op.drop_table('usuarios2')
    op.drop_index(op.f('ix_aluno1_id'), table_name='aluno1')
    op.drop_table('aluno1')
    op.drop_index(op.f('ix_notebook1_id'), table_name='notebook1')
    op.drop_table('notebook1')
    op.drop_index(op.f('ix_carro1_id'), table_name='carro1')
    op.drop_table('carro1')
    op.drop_index(op.f('ix_usuarios3_id'), table_name='usuarios3')
    op.drop_table('usuarios3')
    op.drop_index(op.f('ix_produtos3_id'), table_name='produtos3')
    op.drop_table('produtos3')
    op.drop_index(op.f('ix_tarefa10_id'), table_name='tarefa10')
    op.drop_table('tarefa10')
    op.drop_index(op.f('ix_token_id'), table_name='token')
    op.drop_index(op.f('ix_token_username'), table_name='token')
    op.drop_table('token')
    op.drop_index(op.f('ix_usuarios_id'), table_name='usuarios')
    op.drop_index(op.f('ix_usuarios_usename'), table_name='usuarios')
    #op.drop_table('usuarios')
    op.drop_index(op.f('ix_produtos2_id'), table_name='produtos2')
    op.drop_table('produtos2')
    op.drop_index(op.f('ix_usuario5_id'), table_name='usuario5')
    op.drop_table('usuario5')
    op.drop_index(op.f('ix_usuario10_id'), table_name='usuario10')
    op.drop_table('usuario10')
    op.drop_index(op.f('ix_receitas_id'), table_name='receitas')
    op.drop_table('receitas')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_table('usuario')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuario',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('dono_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['dono_id'], ['usuarios.id'], name=op.f('usuario_dono_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('usuario_pkey'))
    )
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_table('receitas',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_da_receita', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ingredientes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modo_de_preparo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('receitas_pkey'))
    )
    op.create_index(op.f('ix_receitas_id'), 'receitas', ['id'], unique=False)
    op.create_table('usuario10',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usuario10_pkey'))
    )
    op.create_index(op.f('ix_usuario10_id'), 'usuario10', ['id'], unique=False)
    op.create_table('usuario5',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usuario5_pkey'))
    )
    op.create_index(op.f('ix_usuario5_id'), 'usuario5', ['id'], unique=False)
    op.create_table('produtos2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preco', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('produtos2_pkey'))
    )
    op.create_index(op.f('ix_produtos2_id'), 'produtos2', ['id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('usename', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios_pkey'))
    )
    op.create_index(op.f('ix_usuarios_usename'), 'usuarios', ['usename'], unique=True)
    op.create_index(op.f('ix_usuarios_id'), 'usuarios', ['id'], unique=False)
    op.create_table('token',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('token_pkey'))
    )
    op.create_index(op.f('ix_token_username'), 'token', ['username'], unique=True)
    op.create_index(op.f('ix_token_id'), 'token', ['id'], unique=False)
    op.create_table('tarefa10',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('titulo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('descricao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tarefa10_pkey'))
    )
    op.create_index(op.f('ix_tarefa10_id'), 'tarefa10', ['id'], unique=False)
    op.create_table('produtos3',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('preco', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('produtos3_pkey'))
    )
    op.create_index(op.f('ix_produtos3_id'), 'produtos3', ['id'], unique=False)
    op.create_table('usuarios3',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios3_pkey'))
    )
    op.create_index(op.f('ix_usuarios3_id'), 'usuarios3', ['id'], unique=False)
    op.create_table('carro1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('marca', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('modelo', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('carro1_pkey'))
    )
    op.create_index(op.f('ix_carro1_id'), 'carro1', ['id'], unique=False)
    op.create_table('notebook1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('marca', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('polegadas', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('notebook1_pkey'))
    )
    op.create_index(op.f('ix_notebook1_id'), 'notebook1', ['id'], unique=False)
    op.create_table('aluno1',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('idade', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('turma', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('aluno1_pkey'))
    )
    op.create_index(op.f('ix_aluno1_id'), 'aluno1', ['id'], unique=False)
    op.create_table('usuarios2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('usuarios2_pkey'))
    )
    op.create_index(op.f('ix_usuarios2_id'), 'usuarios2', ['id'], unique=False)
    # ### end Alembic commands ###
