"""exclusao ta coluna ano

Revision ID: 7d350c8b2688
Revises: 9bde3b5c08f2
Create Date: 2025-09-05 15:41:43.710347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d350c8b2688'
down_revision: Union[str, Sequence[str], None] = '9bde3b5c08f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('motos', 'ano')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motos', sa.Column('ano', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
