"""remoçao de dono_id e dono: Mapped[user]

Revision ID: ff12b1be959b
Revises: df0cb7c89391
Create Date: 2025-11-28 20:02:27.696103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff12b1be959b'
down_revision: Union[str, Sequence[str], None] = 'df0cb7c89391'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('motos_dono_id_fkey'), 'motos', type_='foreignkey')
    op.drop_column('motos', 'dono_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('motos', sa.Column('dono_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('motos_dono_id_fkey'), 'motos', 'users', ['dono_id'], ['id'])
    # ### end Alembic commands ###
